### ISSUE TITLE
Permitir varios rangos en un mismo día

### ISSUE THREAD

**Issue by ocarreterom** [alejoar/factorialsucks#2]
Sería útil que se pudiera fichar varios tramos para un mismo día como por ejemplo:
```sh
factorialsucks --ci "9:00" --co "14:00"
factorialsucks --ci "15:00" --co "18:00" # Ahora da error: ❌ Already clocked in
```

**Comment by alejoar** [comment]
Hola @ocarreterom 

No trabajo más para la empresa donde usaban factorial, por lo que no podría probar nuevos cambios de momento. Si quieres abrir otro pull request será bienvenido :) -- o incluso ser colaborador, te puedo añadir.

Un saludo

**Comment by alejoar** [comment]
@ocarreterom acabo de hacer un release con la funcionalidad que pides: https://github.com/alejoar/factorialsucks/releases/tag/v2.1

Para actualizar:
```
brew update
brew upgrade factorialsucks
```

**Comment by ocarreterom** [comment]
Gracias @alejoar ! Funciona perfecto! 👍
